### ISSUE TITLE
Review the service-mpx project

### ISSUE THREAD

**Issue by davereid** [Lullabot/mpx-php#1]
https://github.com/dwsla/service-mpx

* What does it do well?
* What does it not do well?
* What could we learn from?

**Comment by deviantintegral** [comment]
I'd like to relicense our library as MIT so we can easily borrow code from service-mpx if it makes sense.  @davereid you're the only other contributor, that cool?

**Comment by deviantintegral** [comment]
I did a review of this library yesterday. A few notes:

[Stats wise](https://packagist.org/packages/dwsla/service-mpx/stats), it looks like the library is not in use by anyone today. While there's an argument for consolidation, there aren't enough users to really matter.

The code is PHP5.3+, so it could use updating to PHP 7 standards. It's PSR-0, which is a minor cleanup. Code-wise, all "services" extend an `AbstractService` class which would be better with an interface.

I like how it names it's classes after the corresponding MPX service, which matches their documentation better.

The code is pretty good. There's a few code smells:

* Exceptions thrown in `__destruct()` turn into FATALs, which means error reporting for signing out is problematic: https://github.com/dwsla/service-mpx/blob/master/src/Dwsla/Service/Mpx/AuthenticationService.php#L101
* Exceptions are cast to false returns, making error handling harder: https://github.com/dwsla/service-mpx/blob/master/src/Dwsla/Service/Mpx/AuthenticationService.php#L83
* There's no error handling for decoding invalid responses: https://github.com/dwsla/service-mpx/blob/master/src/Dwsla/Service/Mpx/MediaService.php#L130
* As tokens are passed around as strings, there's no easy way to refresh them if they are expired in the middle of a request: https://github.com/dwsla/service-mpx/blob/master/src/Dwsla/Service/Mpx/MediaService.php#L31

My thinking is that fixing these issues is going to break enough of the existing API that it would be akin to a new version. Four our purposes, I think it makes sense to work in our own repo (since we already have much of the code done), and reach out to the maintainer about merging or abandoning one of the two repositories.

**Comment by davereid** [comment]
I did not find any benefit in collaboration or consolidation on my initial research as well.

**Comment by davereid** [comment]
@deviantintegral I would be ok with a MIT license for the project.
