### ISSUE TITLE
Review the mateu-aguilo-bosch/mpx-php project

### ISSUE THREAD

**Issue by davereid** [Lullabot/mpx-php#2]
https://github.com/mateu-aguilo-bosch/mpx-php

- What does it do well?
- What does it not do well?
- What could we learn from?

**Comment by deviantintegral** [comment]
I think we can certainly use it for a docs reference on feeds config. They're pretty good!

It reminds me of one of the first PHP libraries I created, where I assumed you _had_ to have a service container of some kind. We don't need one today with our improved understanding of OOP.

Otherwise, I don't see much that's worth porting given we already have much of this functionality here.
