### ISSUE TITLE
Investigate merging Client and UserSession

### ISSUE THREAD

**Issue by deviantintegral** [Lullabot/mpx-php#28]
~~There's no namespace separation for most of our classes. We should find some commonalities and fix that.~~

> So my proposal is that UserSession would not implement the ClientInterface, but keeping it just for the purpose of managing user session functionality, as sign in and sign out.

**Comment by juanolalla** [comment]
It looks to me that it doesn’t make much sense to have two classes implementing Guzzle ClientInterface . The logic of the Client is implemented mainly in UserSession, except for that only line to force HTTP 200 in Client::request(). So the functionality Client is actually implementing to handle XML from a Response could be done without needing to implement the ClientInterface, and it could have a different name other than Client, more adjusted to its XML utilities purpose.

As the same time UserSession seems confusing. It’s like it’s implementing two different purposes, one is the Client we need, and the other is UserSession functionality, like sign in or sign out. It would be nice to split those in two classes, one being actually the Client, and the other being an UserSession which can be managed by the client as dependency if needed, as the use of acquireToken() in mergeAuth() (if we think this belongs more to UserSession than to the Client).

What do you think?

**Comment by deviantintegral** [comment]
> except for that only line to force HTTP 200 in Client::request()

I should document this, but MPX actually forces this server-side as soon as you request JSON. I think the idea was that if you are requesting XML this would keep the behaviour consistent, but I'm not sure if we'll need XML at all. `cjson` works almost totally out of the box with Symfony's decoder (while the MPX XML uses namespaces, which is not supported by XMLEncoder).

> the other being an UserSession which can be managed by the client as dependency if needed

At one point locally, I had something like this. I thought it made the initial authentication workflow a little tricky. In this case, a user session would have to be optional (as there are various anonymous APIs in MPX). That would mean that if you created a client, and then it was passed through an application, different code in the app wouldn't know the client was associated with a session. For example, in Drupal:

```php
$client = $this->container->get('mpx.client');

....

function loadVideo(Client $client) {
  // We don't know if $client has a user session, so we have to manually check.
  if (!$client->getUserSession()) {
    // Our class now needs a dependency on usernames and passwords to somehow create the session.
  }
}
```

If all API calls are routed through UserSession, then we can typehint against that:

```
$session = $this->container->get('mpx.user_session');

....

function loadVideo(UserSession $session) {
  // We know that $session will let us make an authenticated call.
}
```

The other thing I ran into locally was the co-dependency between Client and user session. User sessions need a client to renew API tokens, but you need to create a client first to be able to create a session.

Make sense? Any obvious things I've missed?

**Comment by juanolalla** [comment]
I'm not sure if there is a problem having a Client implementation with a UserSession as a property, and in case a UserSession needs same exact Client object it could store a reference to that client as well, if not, a new Client object could be created on the fly. Sorry if you has already explained me why this is not a good idea and I haven't understood it.

It's just that I see too different things mixed together in the same class and there is a part of me that doesn't like it

**Comment by juanolalla** [comment]
```php
if (!$client->getUserSession()) {
    // Our class now needs a dependency on usernames and passwords to somehow create the session.
}
```
If I'm understanding this well, a Client object having to create the UserSession is a problem, and then I think we could do that with another class

**Comment by deviantintegral** [comment]
Do you mean like an `AuthenticatedClient` class, so we'd have all three?

I suppose the easy thing to do would be to rename UserSession to AuthenticatedClient if that makes more sense.

**Comment by juanolalla** [comment]
I think UserSession is doing too much different things. It implements GuzzleHttp\ClientInterface, but it needs Client, another Guzzle client implementation in the constructor. That Client is doing almost nothing special as a Client implementation, and it has two utility functions.

So my proposal is that UserSession would not implement the ClientInterface, but keeping it just for the purpose of managing user session functionality, as sign in and sign out. I think we should have the ClientInterface methods all together in just one place, our class Client, rather than delegating twice (i.e: rather than doing $this->client->request in the request method of both classes). If we needed the Client without an UserSession we could instantiate it and use it. If we needed to get it from the UserSession we could too, accessing this property. And if we needed a sort of factory or other class to manage the dependencies, statically or not, between UserSession when they are created, we could do so too.

I think that way it would be better organized, more separated and clean, and more easily testable. I don't know the logic, workflow and future usage as well as you do, so feel free to move ahead if you don't agree with me, even if I don't understand very well why do you think the current design is more convenient :+1:

**Comment by deviantintegral** [comment]
I'm game to try - my thinking is that I get some of the other PRs and issues done first and come back to this. Then, we can compare code complexity reports against a possible implementation.

**Comment by deviantintegral** [comment]
I think this is complete as of #54!
